begin;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  topic text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.post (
  id bigint generated by default as identity primary key,
  title text not null,
  body text,
  image text,
  categories_id bigint references public.categories(id) on delete set null,
  username text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.comment (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.post(id) on delete cascade,
  username text not null,
  text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.vote (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.post(id) on delete cascade,
  username text not null,
  upvote boolean not null,
  created_at timestamptz not null default now(),
  unique (post_id, username)
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 80),
  avatar_url text,
  bio text check (char_length(bio) <= 500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null constraint notifications_recipient_id_fkey references public.profiles(id) on delete cascade,
  actor_id uuid not null constraint notifications_actor_id_fkey references public.profiles(id) on delete cascade,
  post_id bigint not null constraint notifications_post_id_fkey references public.post(id) on delete cascade,
  kind text not null check (kind in ('comment')),
  read_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.post add column if not exists user_id uuid;
alter table public.post add column if not exists updated_at timestamptz not null default now();
alter table public.comment add column if not exists user_id uuid;
alter table public.comment add column if not exists updated_at timestamptz not null default now();
alter table public.vote add column if not exists user_id uuid;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'post_user_id_fkey') then
    alter table public.post add constraint post_user_id_fkey foreign key (user_id) references public.profiles(id) on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'comment_user_id_fkey') then
    alter table public.comment add constraint comment_user_id_fkey foreign key (user_id) references public.profiles(id) on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'vote_user_id_fkey') then
    alter table public.vote add constraint vote_user_id_fkey foreign key (user_id) references public.profiles(id) on delete cascade;
  end if;
end $$;

alter table public.post drop constraint if exists post_title_length;
alter table public.post add constraint post_title_length check (char_length(btrim(title)) between 1 and 200);
alter table public.post drop constraint if exists post_body_length;
alter table public.post add constraint post_body_length check (body is null or char_length(body) <= 20000);
alter table public.comment drop constraint if exists comment_text_length;
alter table public.comment add constraint comment_text_length check (char_length(btrim(text)) between 1 and 5000);
alter table public.categories drop constraint if exists category_topic_length;
alter table public.categories add constraint category_topic_length check (char_length(btrim(topic)) between 1 and 60);

alter table public.vote drop constraint if exists vote_post_id_username_key;
create unique index if not exists vote_post_user_unique on public.vote(post_id, user_id) where user_id is not null;
create index if not exists post_user_id_idx on public.post(user_id);
create index if not exists post_feed_cursor_idx on public.post(created_at desc, id desc);
create index if not exists comment_user_id_idx on public.comment(user_id);
create index if not exists vote_user_id_idx on public.vote(user_id);
create index if not exists notifications_recipient_idx on public.notifications(recipient_id, read_at, created_at desc);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, avatar_url)
  values (new.id, left(coalesce(nullif(btrim(new.raw_user_meta_data->>'full_name'), ''), nullif(btrim(new.raw_user_meta_data->>'name'), ''), nullif(split_part(new.email, '@', 1), ''), 'User'), 80), new.raw_user_meta_data->>'avatar_url')
  on conflict (id) do nothing;
  return new;
end;
$$;

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
  for each row execute procedure public.set_updated_at();
drop trigger if exists post_set_updated_at on public.post;
create trigger post_set_updated_at before update on public.post
  for each row execute procedure public.set_updated_at();
drop trigger if exists comment_set_updated_at on public.comment;
create trigger comment_set_updated_at before update on public.comment
  for each row execute procedure public.set_updated_at();

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
  for each row execute procedure public.handle_new_user();

insert into public.profiles (id, display_name, avatar_url)
select id, left(coalesce(nullif(btrim(raw_user_meta_data->>'full_name'), ''), nullif(btrim(raw_user_meta_data->>'name'), ''), nullif(split_part(email, '@', 1), ''), 'User'), 80), raw_user_meta_data->>'avatar_url'
from auth.users on conflict (id) do nothing;

create or replace function public.ensure_my_profile()
returns public.profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  auth_user auth.users%rowtype;
  result public.profiles%rowtype;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  select * into auth_user from auth.users where id = auth.uid();
  if auth_user.id is null then raise exception 'Authenticated user not found'; end if;

  insert into public.profiles (id, display_name, avatar_url)
  values (
    auth_user.id,
    left(coalesce(nullif(btrim(auth_user.raw_user_meta_data->>'full_name'), ''), nullif(btrim(auth_user.raw_user_meta_data->>'name'), ''), nullif(split_part(auth_user.email, '@', 1), ''), 'User'), 80),
    auth_user.raw_user_meta_data->>'avatar_url'
  )
  on conflict (id) do update set avatar_url = coalesce(public.profiles.avatar_url, excluded.avatar_url)
  returning * into result;
  return result;
end;
$$;

revoke all on function public.ensure_my_profile() from public, anon;
grant execute on function public.ensure_my_profile() to authenticated;

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.post enable row level security;
alter table public.comment enable row level security;
alter table public.vote enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "anon all categories" on public.categories;
drop policy if exists "anon all post" on public.post;
drop policy if exists "anon all comment" on public.comment;
drop policy if exists "anon all vote" on public.vote;

drop policy if exists "profiles are public" on public.profiles;
drop policy if exists "users update own profile" on public.profiles;
create policy "profiles are public" on public.profiles for select using (true);
create policy "users update own profile" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "categories are public" on public.categories;
drop policy if exists "authenticated users create categories" on public.categories;
create policy "categories are public" on public.categories for select using (true);
create policy "authenticated users create categories" on public.categories for insert to authenticated with check (auth.uid() is not null);

drop policy if exists "posts are public" on public.post;
drop policy if exists "users create own posts" on public.post;
drop policy if exists "users update own posts" on public.post;
drop policy if exists "users delete own posts" on public.post;
create policy "posts are public" on public.post for select using (true);
create policy "users create own posts" on public.post for insert to authenticated with check (user_id = auth.uid());
create policy "users update own posts" on public.post for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "users delete own posts" on public.post for delete to authenticated using (user_id = auth.uid());

drop policy if exists "comments are public" on public.comment;
drop policy if exists "users create own comments" on public.comment;
drop policy if exists "users update own comments" on public.comment;
drop policy if exists "users delete own comments" on public.comment;
create policy "comments are public" on public.comment for select using (true);
create policy "users create own comments" on public.comment for insert to authenticated with check (user_id = auth.uid());
create policy "users update own comments" on public.comment for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "users delete own comments" on public.comment for delete to authenticated using (user_id = auth.uid());

drop policy if exists "votes are public" on public.vote;
drop policy if exists "users create own votes" on public.vote;
drop policy if exists "users update own votes" on public.vote;
drop policy if exists "users delete own votes" on public.vote;
create policy "votes are public" on public.vote for select using (true);
create policy "users create own votes" on public.vote for insert to authenticated with check (user_id = auth.uid());
create policy "users update own votes" on public.vote for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "users delete own votes" on public.vote for delete to authenticated using (user_id = auth.uid());

drop policy if exists "users read own notifications" on public.notifications;
drop policy if exists "users update own notifications" on public.notifications;
drop policy if exists "users delete own notifications" on public.notifications;
create policy "users read own notifications" on public.notifications for select to authenticated using (recipient_id = auth.uid());
create policy "users update own notifications" on public.notifications for update to authenticated using (recipient_id = auth.uid()) with check (recipient_id = auth.uid());
create policy "users delete own notifications" on public.notifications for delete to authenticated using (recipient_id = auth.uid());

create or replace function public.notify_on_comment()
returns trigger language plpgsql security definer set search_path = public
as $$
declare post_owner uuid;
begin
  select user_id into post_owner from public.post where id = new.post_id;
  if post_owner is not null and new.user_id is not null and post_owner <> new.user_id then
    insert into public.notifications (recipient_id, actor_id, post_id, kind)
    values (post_owner, new.user_id, new.post_id, 'comment');
  end if;
  return new;
end;
$$;

drop trigger if exists comment_notification on public.comment;
create trigger comment_notification after insert on public.comment
  for each row execute procedure public.notify_on_comment();

create or replace function public.search_posts(search_text text, result_limit integer default 20, result_offset integer default 0)
returns setof public.post language sql stable security invoker set search_path = public
as $$
  select p.* from public.post p
  left join public.categories c on c.id = p.categories_id
  where char_length(btrim(search_text)) between 1 and 100
    and (p.title ilike '%' || btrim(search_text) || '%' or c.topic ilike '%' || btrim(search_text) || '%')
  order by p.created_at desc, p.id desc
  limit least(greatest(result_limit, 1), 50) offset greatest(result_offset, 0);
$$;

create or replace function public.feed_posts(
  filter_topic text default null,
  filter_user uuid default null,
  sort_by text default 'newest',
  result_limit integer default 20,
  result_offset integer default 0
)
returns setof public.post language sql stable security invoker set search_path = public
as $$
  select p.* from public.post p
  left join public.categories c on c.id = p.categories_id
  where (filter_topic is null or lower(c.topic) = lower(filter_topic))
    and (filter_user is null or p.user_id = filter_user)
    and (
      sort_by not in ('top_day', 'top_week')
      or (sort_by = 'top_day' and p.created_at >= now() - interval '1 day')
      or (sort_by = 'top_week' and p.created_at >= now() - interval '7 days')
    )
  order by
    case when sort_by in ('top_day', 'top_week', 'top_all') then
      coalesce((select sum(case when v.upvote then 1 else -1 end) from public.vote v where v.post_id = p.id), 0)
    end desc,
    p.created_at desc,
    p.id desc
  limit least(greatest(result_limit, 1), 50) offset greatest(result_offset, 0);
$$;

create or replace function public.top_categories(result_limit integer default 5)
returns table (id bigint, topic text, post_count bigint)
language sql stable security invoker set search_path = public
as $$
  select c.id, c.topic, count(p.id)::bigint from public.categories c
  join public.post p on p.categories_id = c.id
  group by c.id, c.topic order by count(p.id) desc, c.topic asc
  limit least(greatest(result_limit, 1), 20);
$$;

grant execute on function public.search_posts(text, integer, integer) to anon, authenticated;
grant execute on function public.feed_posts(text, uuid, text, integer, integer) to anon, authenticated;
grant execute on function public.top_categories(integer) to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('post-images', 'post-images', true, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "users upload own post images" on storage.objects;
drop policy if exists "users update own post images" on storage.objects;
drop policy if exists "users delete own post images" on storage.objects;
create policy "users upload own post images" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'post-images' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "users update own post images" on storage.objects
  for update to authenticated
  using (bucket_id = 'post-images' and owner_id = auth.uid()::text)
  with check (bucket_id = 'post-images' and owner_id = auth.uid()::text);
create policy "users delete own post images" on storage.objects
  for delete to authenticated
  using (bucket_id = 'post-images' and owner_id = auth.uid()::text);

commit;
